ALTER TABLE "practice_modes" ADD COLUMN "prompt_instructions" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "question_types" ADD COLUMN "prompt_instructions" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "interview_styles" ADD COLUMN "prompt_instructions" text DEFAULT '' NOT NULL;--> statement-breakpoint
UPDATE "practice_modes" SET "prompt_instructions" = 'Run this as a short opening-impression practice. Ask for a concise introduction or tell me about yourself style answer, then help the candidate make the opening clear, confident, and role-relevant.' WHERE "key" = 'first_impression';--> statement-breakpoint
UPDATE "practice_modes" SET "prompt_instructions" = 'Run this as an interactive coaching session. Ask one focused question, let the candidate answer, give brief actionable coaching, then ask a tighter follow-up or retry prompt.' WHERE "key" = 'coaching';--> statement-breakpoint
UPDATE "practice_modes" SET "prompt_instructions" = 'Run this as paced repetition. Ask short interview questions one at a time, keep feedback minimal between answers, and help the candidate build speed, composure, and recovery.' WHERE "key" = 'rapid_fire';--> statement-breakpoint
UPDATE "practice_modes" SET "prompt_instructions" = 'Run this as a realistic interview simulation. Ask one question at a time, avoid coaching during the interview unless the candidate asks, and keep the flow professional.' WHERE "key" = 'mock_interview';--> statement-breakpoint
UPDATE "question_types" SET "prompt_instructions" = 'Focus on past experience, behavior, collaboration, conflict, leadership, ownership, and examples with enough context, action, and result.' WHERE "key" = 'behavioral';--> statement-breakpoint
UPDATE "question_types" SET "prompt_instructions" = 'Focus on role-relevant technical depth. Ask the candidate to explain decisions, tradeoffs, troubleshooting, systems, tools, or methods clearly for the target role.' WHERE "key" = 'technical';--> statement-breakpoint
UPDATE "question_types" SET "prompt_instructions" = 'Focus on how the candidate would reason through a realistic future scenario. Look for structure, assumptions, tradeoffs, and practical next steps.' WHERE "key" = 'hypothetical';--> statement-breakpoint
UPDATE "question_types" SET "prompt_instructions" = 'Focus on motivation, fit, goals, company interest, role interest, and the candidate ability to connect their background to the opportunity.' WHERE "key" = 'motivational';--> statement-breakpoint
UPDATE "interview_styles" SET "prompt_instructions" = 'Use a warm, encouraging tone. Keep pressure low, affirm useful pieces of the answer, and offer constructive guidance without sounding soft or vague.' WHERE "key" = 'friendly';--> statement-breakpoint
UPDATE "interview_styles" SET "prompt_instructions" = 'Use a calm, professional interviewer tone. Keep feedback balanced and direct, with realistic follow-ups and no exaggerated praise.' WHERE "key" = 'neutral';--> statement-breakpoint
UPDATE "interview_styles" SET "prompt_instructions" = 'Use a direct, higher-pressure interviewer tone. Ask sharper follow-ups, challenge vague answers, and stay professional rather than harsh.' WHERE "key" = 'tough';
