INSERT INTO study_audience_tags (label, slug, sort_order)
VALUES
  ('General / Curious', 'general-curious', 10),
  ('High School', 'high-school', 20),
  ('AP Exam Prep', 'ap-exam-prep', 30),
  ('MCAT Prep', 'mcat-prep', 40),
  ('NCLEX / Nursing', 'nclex-nursing', 50),
  ('Medical School', 'medical-school', 60),
  ('EMT / Paramedic', 'emt-paramedic', 70),
  ('Pharmacy (NAPLEX)', 'pharmacy-naplex', 80),
  ('Radiology', 'radiology', 90),
  ('Aviation (PPL/CPL)', 'aviation-ppl-cpl', 100),
  ('Aviation (Part 135)', 'aviation-part-135', 110),
  ('Law School', 'law-school', 120),
  ('Bar Exam', 'bar-exam', 130),
  ('Real Estate Exam', 'real-estate-exam', 140),
  ('Personal Interest', 'personal-interest', 150)
ON CONFLICT (slug) DO UPDATE
SET label = EXCLUDED.label,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();

INSERT INTO study_trusted_sources (name, domain, kind)
VALUES
  ('CDC', 'cdc.gov', 'canonical'),
  ('NIH / NLM', 'nlm.nih.gov', 'canonical'),
  ('FDA', 'fda.gov', 'canonical'),
  ('WHO', 'who.int', 'canonical'),
  ('AHA', 'heart.org', 'canonical'),
  ('NCSBN', 'ncsbn.org', 'canonical'),
  ('NCBI', 'ncbi.nlm.nih.gov', 'canonical'),
  ('UniProt', 'uniprot.org', 'canonical'),
  ('PubMed Central', 'pmc.ncbi.nlm.nih.gov', 'canonical'),
  ('FAA', 'faa.gov', 'canonical'),
  ('ICAO', 'icao.int', 'canonical'),
  ('Cornell LII', 'law.cornell.edu', 'canonical'),
  ('OpenStax', 'openstax.org', 'canonical'),
  ('GovInfo', 'govinfo.gov', 'canonical'),
  ('PubMed', 'pubmed.ncbi.nlm.nih.gov', 'canonical'),
  ('Mayo Clinic', 'mayoclinic.org', 'corroborated'),
  ('Cleveland Clinic', 'my.clevelandclinic.org', 'corroborated'),
  ('Johns Hopkins Health', 'hopkinsmedicine.org', 'corroborated'),
  ('Khan Academy', 'khanacademy.org', 'corroborated'),
  ('MedlinePlus', 'medlineplus.gov', 'corroborated')
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE study_subject_seed (
  name text NOT NULL,
  slug text NOT NULL,
  parent_slug text,
  sort_order integer NOT NULL
) ON COMMIT DROP;

INSERT INTO study_subject_seed (name, slug, parent_slug, sort_order)
VALUES
  ('Biology', 'biology', NULL, 100),
  ('Cell Biology', 'cell-biology', 'biology', 101),
  ('Organelles', 'organelles', 'cell-biology', 102),
  ('Cell Membrane & Transport', 'cell-membrane-transport', 'cell-biology', 103),
  ('DNA Replication', 'dna-replication', 'cell-biology', 104),
  ('Protein Synthesis', 'protein-synthesis', 'cell-biology', 105),
  ('Cell Division', 'cell-division', 'cell-biology', 106),
  ('Genetics', 'genetics', 'biology', 110),
  ('Mendelian Genetics', 'mendelian-genetics', 'genetics', 111),
  ('Molecular Genetics', 'molecular-genetics', 'genetics', 112),
  ('Population Genetics', 'population-genetics', 'genetics', 113),
  ('Ecology', 'ecology', 'biology', 120),
  ('Ecosystems', 'ecosystems', 'ecology', 121),
  ('Biomes', 'biomes', 'ecology', 122),
  ('Population Ecology', 'population-ecology', 'ecology', 123),
  ('Evolution', 'evolution', 'biology', 130),
  ('Natural Selection', 'natural-selection', 'evolution', 131),
  ('Speciation', 'speciation', 'evolution', 132),
  ('Phylogenetics', 'phylogenetics', 'evolution', 133),
  ('Microbiology', 'microbiology', 'biology', 140),
  ('Bacteria', 'bacteria', 'microbiology', 141),
  ('Viruses', 'viruses', 'microbiology', 142),
  ('Fungi & Parasites', 'fungi-parasites', 'microbiology', 143),

  ('Medicine & Health', 'medicine-health', NULL, 200),
  ('Anatomy & Physiology', 'anatomy-physiology', 'medicine-health', 201),
  ('Cardiovascular System', 'cardiovascular-system', 'anatomy-physiology', 202),
  ('Respiratory System', 'respiratory-system', 'anatomy-physiology', 203),
  ('Nervous System', 'nervous-system', 'anatomy-physiology', 204),
  ('Musculoskeletal System', 'musculoskeletal-system', 'anatomy-physiology', 205),
  ('Renal System', 'renal-system', 'anatomy-physiology', 206),
  ('Endocrine System', 'endocrine-system', 'anatomy-physiology', 207),
  ('Digestive System', 'digestive-system', 'anatomy-physiology', 208),
  ('Reproductive System', 'reproductive-system', 'anatomy-physiology', 209),
  ('Integumentary System', 'integumentary-system', 'anatomy-physiology', 210),
  ('Pharmacology', 'pharmacology', 'medicine-health', 220),
  ('Drug Classes', 'drug-classes', 'pharmacology', 221),
  ('Drug Interactions', 'drug-interactions', 'pharmacology', 222),
  ('Pharmacokinetics', 'pharmacokinetics', 'pharmacology', 223),
  ('Pharmacodynamics', 'pharmacodynamics', 'pharmacology', 224),
  ('Pathology', 'pathology', 'medicine-health', 230),
  ('Infectious Disease', 'infectious-disease', 'pathology', 231),
  ('Oncology', 'oncology', 'pathology', 232),
  ('Cardiovascular Disease', 'cardiovascular-disease', 'pathology', 233),
  ('Autoimmune Disease', 'autoimmune-disease', 'pathology', 234),
  ('Nursing', 'nursing', 'medicine-health', 240),
  ('Med-Surg Nursing', 'med-surg-nursing', 'nursing', 241),
  ('Pediatric Nursing', 'pediatric-nursing', 'nursing', 242),
  ('OB / Maternal Nursing', 'ob-maternal-nursing', 'nursing', 243),
  ('Psychiatric Nursing', 'psychiatric-nursing', 'nursing', 244),
  ('Critical Care Nursing', 'critical-care-nursing', 'nursing', 245),
  ('Emergency Medicine', 'emergency-medicine', 'medicine-health', 250),
  ('Trauma', 'trauma', 'emergency-medicine', 251),
  ('Toxicology', 'toxicology', 'emergency-medicine', 252),
  ('Cardiac Emergencies', 'cardiac-emergencies', 'emergency-medicine', 253),
  ('Airway Management', 'airway-management', 'emergency-medicine', 254),

  ('Chemistry', 'chemistry', NULL, 300),
  ('General Chemistry', 'general-chemistry', 'chemistry', 301),
  ('Atomic Structure', 'atomic-structure', 'general-chemistry', 302),
  ('Chemical Bonding', 'chemical-bonding', 'general-chemistry', 303),
  ('Stoichiometry', 'stoichiometry', 'general-chemistry', 304),
  ('Thermochemistry', 'thermochemistry', 'general-chemistry', 305),
  ('Equilibrium', 'equilibrium', 'general-chemistry', 306),
  ('Organic Chemistry', 'organic-chemistry', 'chemistry', 310),
  ('Functional Groups', 'functional-groups', 'organic-chemistry', 311),
  ('Reaction Mechanisms', 'reaction-mechanisms', 'organic-chemistry', 312),
  ('Stereochemistry', 'stereochemistry', 'organic-chemistry', 313),
  ('Spectroscopy', 'spectroscopy', 'organic-chemistry', 314),
  ('Biochemistry', 'biochemistry', 'chemistry', 320),
  ('Amino Acids & Proteins', 'amino-acids-proteins', 'biochemistry', 321),
  ('Enzymes', 'enzymes', 'biochemistry', 322),
  ('Metabolism', 'metabolism', 'biochemistry', 323),
  ('Nucleic Acids', 'nucleic-acids', 'biochemistry', 324),

  ('Physics', 'physics', NULL, 400),
  ('Classical Mechanics', 'classical-mechanics', 'physics', 401),
  ('Kinematics', 'kinematics', 'classical-mechanics', 402),
  ('Forces & Newton''s Laws', 'forces-newton-s-laws', 'classical-mechanics', 403),
  ('Energy & Work', 'energy-work', 'classical-mechanics', 404),
  ('Momentum', 'momentum', 'classical-mechanics', 405),
  ('Thermodynamics', 'thermodynamics', 'physics', 410),
  ('Laws of Thermodynamics', 'laws-of-thermodynamics', 'thermodynamics', 411),
  ('Heat Transfer', 'heat-transfer', 'thermodynamics', 412),
  ('Entropy', 'entropy', 'thermodynamics', 413),
  ('Electromagnetism', 'electromagnetism', 'physics', 420),
  ('Electric Fields', 'electric-fields', 'electromagnetism', 421),
  ('Circuits', 'circuits', 'electromagnetism', 422),
  ('Magnetism', 'magnetism', 'electromagnetism', 423),
  ('Electromagnetic Waves', 'electromagnetic-waves', 'electromagnetism', 424),
  ('Optics', 'optics', 'physics', 430),
  ('Geometric Optics', 'geometric-optics', 'optics', 431),
  ('Wave Optics', 'wave-optics', 'optics', 432),

  ('Psychology', 'psychology', NULL, 500),
  ('Abnormal Psychology', 'abnormal-psychology', 'psychology', 501),
  ('Mood Disorders', 'mood-disorders', 'abnormal-psychology', 502),
  ('Anxiety Disorders', 'anxiety-disorders', 'abnormal-psychology', 503),
  ('Psychotic Disorders', 'psychotic-disorders', 'abnormal-psychology', 504),
  ('Personality Disorders', 'personality-disorders', 'abnormal-psychology', 505),
  ('Social Psychology', 'social-psychology', 'psychology', 510),
  ('Attitudes & Persuasion', 'attitudes-persuasion', 'social-psychology', 511),
  ('Group Dynamics', 'group-dynamics', 'social-psychology', 512),
  ('Conformity & Obedience', 'conformity-obedience', 'social-psychology', 513),
  ('Cognitive Psychology', 'cognitive-psychology', 'psychology', 520),
  ('Memory', 'memory', 'cognitive-psychology', 521),
  ('Attention', 'attention', 'cognitive-psychology', 522),
  ('Language', 'language', 'cognitive-psychology', 523),
  ('Problem Solving', 'problem-solving', 'cognitive-psychology', 524),
  ('Developmental Psychology', 'developmental-psychology', 'psychology', 530),
  ('Child Development', 'child-development', 'developmental-psychology', 531),
  ('Adolescence', 'adolescence', 'developmental-psychology', 532),
  ('Adulthood & Aging', 'adulthood-aging', 'developmental-psychology', 533),

  ('Aviation', 'aviation', NULL, 600),
  ('FAA Regulations', 'faa-regulations', 'aviation', 601),
  ('Part 61 - Pilot Certification', 'part-61-pilot-certification', 'faa-regulations', 602),
  ('Part 91 - General Operating Rules', 'part-91-general-operating-rules', 'faa-regulations', 603),
  ('Part 135 - Charter Operations', 'part-135-charter-operations', 'faa-regulations', 604),
  ('AIM - Aeronautical Information', 'aim-aeronautical-information', 'faa-regulations', 605),
  ('Meteorology', 'meteorology', 'aviation', 610),
  ('Weather Patterns', 'weather-patterns', 'meteorology', 611),
  ('Clouds & Precipitation', 'clouds-precipitation', 'meteorology', 612),
  ('Hazardous Weather', 'hazardous-weather', 'meteorology', 613),
  ('METARs & TAFs', 'metars-tafs', 'meteorology', 614),
  ('Navigation', 'navigation', 'aviation', 620),
  ('VOR / NDB', 'vor-ndb', 'navigation', 621),
  ('GPS & RNAV', 'gps-rnav', 'navigation', 622),
  ('Charts & Airspace', 'charts-airspace', 'navigation', 623),
  ('IFR Procedures', 'ifr-procedures', 'navigation', 624),
  ('Aircraft Systems', 'aircraft-systems', 'aviation', 630),
  ('Powerplant', 'powerplant', 'aircraft-systems', 631),
  ('Airframe', 'airframe', 'aircraft-systems', 632),
  ('Avionics', 'avionics', 'aircraft-systems', 633),
  ('Fuel Systems', 'fuel-systems', 'aircraft-systems', 634),
  ('Hydraulics', 'hydraulics', 'aircraft-systems', 635),
  ('Flight Operations', 'flight-operations', 'aviation', 640),
  ('Preflight', 'preflight', 'flight-operations', 641),
  ('Emergency Procedures', 'emergency-procedures', 'flight-operations', 642),
  ('Weight & Balance', 'weight-balance', 'flight-operations', 643),
  ('Performance', 'performance', 'flight-operations', 644),

  ('Law', 'law', NULL, 700),
  ('Constitutional Law', 'constitutional-law', 'law', 701),
  ('First Amendment', 'first-amendment', 'constitutional-law', 702),
  ('Due Process', 'due-process', 'constitutional-law', 703),
  ('Equal Protection', 'equal-protection', 'constitutional-law', 704),
  ('Commerce Clause', 'commerce-clause', 'constitutional-law', 705),
  ('Contract Law', 'contract-law', 'law', 710),
  ('Formation', 'formation', 'contract-law', 711),
  ('Consideration', 'consideration', 'contract-law', 712),
  ('Breach & Remedies', 'breach-remedies', 'contract-law', 713),
  ('Defenses', 'defenses', 'contract-law', 714),
  ('Torts', 'torts', 'law', 720),
  ('Negligence', 'negligence', 'torts', 721),
  ('Intentional Torts', 'intentional-torts', 'torts', 722),
  ('Strict Liability', 'strict-liability', 'torts', 723),
  ('Products Liability', 'products-liability', 'torts', 724),
  ('Criminal Law', 'criminal-law', 'law', 730),
  ('Elements of Crimes', 'elements-of-crimes', 'criminal-law', 731),
  ('Criminal Defenses', 'criminal-defenses', 'criminal-law', 732),
  ('Homicide', 'homicide', 'criminal-law', 733),
  ('Property Crimes', 'property-crimes', 'criminal-law', 734),
  ('Civil Procedure', 'civil-procedure', 'law', 740),
  ('Jurisdiction', 'jurisdiction', 'civil-procedure', 741),
  ('Pleadings', 'pleadings', 'civil-procedure', 742),
  ('Discovery', 'discovery', 'civil-procedure', 743),
  ('Trial & Appeals', 'trial-appeals', 'civil-procedure', 744),
  ('Property Law', 'property-law', 'law', 750),
  ('Real Property', 'real-property', 'property-law', 751),
  ('Personal Property', 'personal-property', 'property-law', 752),
  ('Landlord-Tenant', 'landlord-tenant', 'property-law', 753),
  ('Estates & Trusts', 'estates-trusts', 'property-law', 754);

INSERT INTO study_subjects (name, slug, parent_id, sort_order)
SELECT seed.name, seed.slug, parent.id, seed.sort_order
FROM study_subject_seed seed
LEFT JOIN study_subjects parent ON parent.slug = seed.parent_slug
WHERE seed.parent_slug IS NULL OR parent.id IS NOT NULL
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    parent_id = EXCLUDED.parent_id,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();
