import { router, useLocalSearchParams } from "expo-router";
import { ArrowLeft, ChevronDown, ChevronUp } from "lucide-react-native";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Card } from "@/components/ui/card";
import { Screen } from "@/components/ui/screen";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useBootstrap } from "@/lib/bootstrap";
import { colors, radius, spacing } from "@/theme/tokens";

export default function ReviewScreen() {
  const { sessionId } = useLocalSearchParams<{ sessionId: string }>(); const bootstrap = useBootstrap(); const [showTranscript, setShowTranscript] = useState(false);
  if (bootstrap.isLoading) return <LoadingState label="Opening review…" />;
  const session = bootstrap.data?.sessions.find((item) => item.id === sessionId);
  if (!session) return <ErrorState message="This saved review could not be found." onRetry={() => { router.back(); }} />;
  const review = session.evaluation; const overall = review?.scores.length ? Math.round(review.scores.reduce((sum, score) => sum + score.score, 0) / review.scores.length * 20) : undefined;
  return <Screen eyebrow="Saved review" title={session.targetRole || "Interview practice"} trailing={<Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><ArrowLeft color={colors.text} size={22} /></Pressable>}>
    <Card accent={review ? "lime" : undefined}>
      <View style={styles.scoreRow}><Text style={styles.score}>{overall ? `${overall}` : "—"}</Text><View><Text style={styles.scoreUnit}>{overall ? "/ 100" : "Not scored"}</Text><Text style={styles.muted}>{session.evaluationStatus === "too_short" ? "Session saved; continue for 2+ minutes to receive coaching." : "Overall interview score"}</Text></View></View>
    </Card>
    {review ? <><Card title="Coach summary"><Text style={styles.body}>{review.summary}</Text><Text style={styles.insight}>{review.coachingInsight}</Text></Card><Card title="Five dimensions">{review.scores.map((score) => <View key={score.key} style={styles.dimension}><View style={styles.dimensionTop}><Text style={styles.dimensionLabel}>{score.label}</Text><Text style={styles.dimensionScore}>{score.score}/5</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${score.score * 20}%` }]} /></View><Text style={styles.muted}>{score.summary}</Text></View>)}</Card>{review.reviewDetail?.strengths.length ? <ListCard items={review.reviewDetail.strengths} title="Strengths" /> : null}{review.reviewDetail?.focusAreas.length ? <ListCard items={review.reviewDetail.focusAreas} title="Focus next" /> : null}{review.reviewDetail?.practicePlan.length ? <ListCard items={review.reviewDetail.practicePlan} title="Practice plan" /> : null}</> : <Card title="Review status"><Text style={styles.body}>{session.evaluationError || (session.evaluationStatus === "too_short" ? "This session was safely saved, but it was shorter than the two-minute scoring threshold." : "QuesIQ is still preparing this review. Pull down on History shortly to refresh.")}</Text></Card>}
    <Card><Pressable onPress={() => setShowTranscript((value) => !value)} style={styles.transcriptToggle}><Text style={styles.dimensionLabel}>Transcript · {session.transcript.length} turns</Text>{showTranscript ? <ChevronUp color={colors.cyan} /> : <ChevronDown color={colors.cyan} />}</Pressable>{showTranscript ? session.transcript.map((turn) => <View key={turn.id} style={[styles.turn, turn.role === "assistant" && styles.que]}><Text style={styles.speaker}>{turn.speaker}</Text><Text style={styles.body}>{turn.text}</Text></View>) : null}</Card>
  </Screen>;
}
function ListCard({ items, title }: { items: string[]; title: string }) { return <Card title={title}>{items.map((item, index) => <View key={`${title}-${index}`} style={styles.listRow}><Text style={styles.bullet}>•</Text><Text style={styles.body}>{item}</Text></View>)}</Card>; }
const styles = StyleSheet.create({ back: { alignItems: "center", backgroundColor: colors.panel, borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, height: 46, justifyContent: "center", width: 46 }, body: { color: colors.textSoft, flex: 1, fontSize: 14, lineHeight: 21 }, bullet: { color: colors.lime, fontSize: 20 }, dimension: { gap: spacing.xs, paddingVertical: spacing.xs }, dimensionLabel: { color: colors.text, fontSize: 15, fontWeight: "800" }, dimensionScore: { color: colors.cyan, fontSize: 14, fontWeight: "900" }, dimensionTop: { flexDirection: "row", justifyContent: "space-between" }, fill: { backgroundColor: colors.cyan, borderRadius: 99, height: "100%" }, insight: { color: colors.lime, fontSize: 15, fontWeight: "700", lineHeight: 22 }, listRow: { flexDirection: "row", gap: spacing.sm }, muted: { color: colors.muted, fontSize: 13, lineHeight: 19 }, que: { borderLeftColor: colors.cyan }, score: { color: colors.lime, fontSize: 54, fontWeight: "900", letterSpacing: -2 }, scoreRow: { alignItems: "center", flexDirection: "row", gap: spacing.md }, scoreUnit: { color: colors.text, fontSize: 18, fontWeight: "800" }, speaker: { color: colors.cyan, fontSize: 11, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, track: { backgroundColor: colors.backgroundRaised, borderRadius: 99, height: 8, overflow: "hidden" }, transcriptToggle: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 44 }, turn: { borderLeftColor: colors.borderStrong, borderLeftWidth: 2, gap: spacing.xs, paddingLeft: spacing.md, paddingVertical: spacing.sm } });
