import type { CoachingAttempt, SessionDetail } from "@quesiq/interview-contracts";
import { router, useLocalSearchParams } from "expo-router";
import { ArrowLeft, ChevronDown, ChevronUp } from "lucide-react-native";
import { useMemo, useState } from "react";
import { Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Screen } from "@/components/ui/screen";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { reviewError, useRequestReview, useReview } from "@/lib/review-history";
import { colors, radius, spacing } from "@/theme/tokens";

export default function ReviewScreen() {
  const { sessionId, attemptId, turnIndex } = useLocalSearchParams<{ sessionId: string; attemptId?: string; turnIndex?: string }>();
  const reviewQuery = useReview(sessionId); const requestReview = useRequestReview(sessionId); const [showTranscript, setShowTranscript] = useState(false); const [confirmation, setConfirmation] = useState(false); const [linkedTurn, setLinkedTurn] = useState<string>();
  if (reviewQuery.isLoading) return <LoadingState label="Opening review…" />;
  if (reviewQuery.isError || !reviewQuery.data) return <ErrorState message={reviewError(reviewQuery.error)} onRetry={() => reviewQuery.refetch()} />;
  const session = reviewQuery.data; const review = session.evaluation; const overall = review?.scores.length ? Math.round(review.scores.reduce((sum, score) => sum + score.score, 0) / review.scores.length * 20) : undefined;
  const linkedEvidence = session.progressEvidence?.find(row => attemptId ? row.id === attemptId : turnIndex !== undefined && row.turnIndex === Number(turnIndex));
  return <Screen eyebrow="Saved review" title={session.targetRole || "Interview practice"} trailing={<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><ArrowLeft color={colors.text} size={22} /></Pressable>} refreshControl={<RefreshControl colors={[colors.cyan]} onRefresh={() => reviewQuery.refetch()} refreshing={reviewQuery.isRefetching} tintColor={colors.cyan} />}>
    <Card title="Review status"><Text style={styles.body}>{requestReview.errorMessage ?? session.reviewAccess.message}</Text>{session.reviewAccess.canRequest ? <Button disabled={requestReview.isPending} label={requestReview.isPending ? "Requesting review…" : confirmation ? "Confirm evaluation request" : "Request review"} onPress={() => { if (!confirmation) setConfirmation(true); else { setConfirmation(false); requestReview.mutate(); } }} /> : null}</Card>
    {confirmation ? <Text style={styles.muted}>This explicitly requests an AI evaluation and may incur AI usage.</Text> : null}
    {linkedEvidence ? <Card accent="cyan" title="Linked supporting answer"><Text style={styles.dimensionLabel}>{linkedEvidence.question}</Text><Text style={styles.muted}>{linkedEvidence.classification === "guided_retry" ? "Guided retry" : linkedEvidence.classification === "repeated" ? "Repeated practice" : "Initial answer"}</Text><Text style={styles.body}>{linkedEvidence.answer}</Text>{linkedEvidence.finding ? <Text style={styles.body}>{linkedEvidence.finding}</Text> : null}{linkedEvidence.improvement ? <Text style={styles.insight}>{linkedEvidence.improvement}</Text> : null}</Card> : attemptId || turnIndex !== undefined ? <Text style={styles.muted}>This exact evidence link is unavailable. The historical transcript remains below.</Text> : null}
    {session.provenance !== "learner" ? <Text style={styles.muted}>Historical provenance is {session.provenance ?? "unknown"}. This record does not establish verified progress.</Text> : null}
    {session.preparationHistory?.length ? <Card title="Preparation copied for this session">{session.preparationHistory.map((item, index) => <Text key={`${item.title}-${index}`} style={styles.muted}>{item.title} · revision {item.revision ?? "unknown"} · {item.status === "deleted" ? "Deleted from your library. This historical copy remains; it is not used in future practice." : item.status === "changed" ? "Changed since this session; the original copy is preserved." : "Saved historical copy"}</Text>)}</Card> : null}
    {review ? <ReviewContent onOpenTranscript={(id) => { setLinkedTurn(id); setShowTranscript(true); }} overall={overall} session={session} /> : null}
    <AttemptComparison attempts={session.attempts} />
    <Button label="Save questions from this session" variant="secondary" onPress={() => router.push({ pathname: "/questions", params: { sessionId } })} />
    <Transcript linkedTurn={linkedTurn} open={showTranscript} onToggle={() => setShowTranscript((value) => !value)} session={session} />
  </Screen>;
}

function ReviewContent({ onOpenTranscript, overall, session }: { onOpenTranscript: (id: string) => void; overall?: number; session: SessionDetail }) {
  const review = session.evaluation!; const evidence = (review.reviewDetail?.evidence ?? review.scores.flatMap((score) => score.evidence ? [score.evidence] : [])).map((quote) => quote.trim()).filter(Boolean);
  return <><Card accent="lime" title="Next practice step"><Text style={styles.insight}>{review.nextAction || review.reviewDetail?.focusAreas[0] || review.coachingInsight}</Text></Card>{evidence.length ? <Card title="Transcript evidence">{evidence.map((quote, index) => { const turn = session.transcript.find((item) => item.text.includes(quote)); return turn ? <Pressable accessibilityRole="button" style={styles.evidenceLink} accessibilityLabel={`Open transcript evidence ${index + 1}`} key={`${quote}-${index}`} onPress={() => onOpenTranscript(turn.id)}><Text style={styles.body}>“{quote}” · {turn.speaker}</Text></Pressable> : <Text key={`${quote}-${index}`} style={styles.body}>“{quote}” · transcript link unavailable</Text>; })}</Card> : null}<Card><View style={styles.scoreRow}><Text style={styles.score}>{overall !== undefined ? `${overall}` : "—"}</Text><View><Text style={styles.scoreUnit}>{overall !== undefined ? "/ 100" : "Not scored"}</Text><Text style={styles.muted}>Overall interview score</Text></View></View></Card><Card title="Coach summary"><Text style={styles.body}>{review.summary}</Text><Text style={styles.insight}>{review.coachingInsight}</Text></Card><Card title="Five dimensions">{review.scores.map((score) => <View key={score.key} style={styles.dimension}><View style={styles.dimensionTop}><Text style={styles.dimensionLabel}>{score.label}</Text><Text style={styles.dimensionScore}>{score.score}/5</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${score.score * 20}%` }]} /></View><Text style={styles.muted}>{score.summary}</Text></View>)}</Card>{review.reviewDetail?.strengths.length ? <ListCard items={review.reviewDetail.strengths} title="Strengths" /> : null}{review.reviewDetail?.focusAreas.length ? <ListCard items={review.reviewDetail.focusAreas} title="Focus next" /> : null}{review.reviewDetail?.practicePlan.length ? <ListCard items={review.reviewDetail.practicePlan} title="Practice plan" /> : null}</>;
}
function AttemptComparison({ attempts = [] }: { attempts?: CoachingAttempt[] }) { const pairs = useMemo(() => Array.from(new Set(attempts.map((attempt) => attempt.questionId))).map((questionId) => { const matching = attempts.filter((attempt) => attempt.questionId === questionId).sort((a, b) => a.attemptIndex - b.attemptIndex); return { first: matching[0], latest: matching.at(-1) }; }).filter((pair): pair is { first: CoachingAttempt; latest: CoachingAttempt } => Boolean(pair.first && pair.latest && pair.first.id !== pair.latest.id)), [attempts]); if (!pairs.length) return null; return <Card title="Same-question attempts">{pairs.map(({ first, latest }) => <View key={first.questionId} style={styles.comparison}><Text style={styles.dimensionLabel}>{first.question}</Text><Text style={styles.muted}>First attempt · {first.assisted ? "Assisted retry" : "Initial answer"}{first.model ? ` · ${first.model}` : ""} · {first.promptProfile} · {first.promptVersions.map((version) => `${version.key} v${version.version}`).join(", ") || "version unavailable"}</Text><Text style={styles.body}>{first.answer}</Text><Text style={styles.muted}>{first.feedback}</Text>{first.priority ? <Text style={styles.assisted}>Priority: {first.priority}</Text> : null}{first.evidence.map((item) => <Text key={`${first.id}-${item.start}`} style={styles.muted}>Evidence: “{item.quote}”</Text>)}<Text style={styles.muted}>Latest attempt · {latest.assisted ? "Assisted retry" : "Initial answer"}{latest.model ? ` · ${latest.model}` : ""} · {latest.promptProfile} · {latest.promptVersions.map((version) => `${version.key} v${version.version}`).join(", ") || "version unavailable"}</Text><Text style={styles.body}>{latest.answer}</Text><Text style={styles.muted}>{latest.feedback}</Text>{latest.priority ? <Text style={styles.assisted}>Priority: {latest.priority}</Text> : null}{latest.evidence.map((item) => <Text key={`${latest.id}-${item.start}`} style={styles.muted}>Evidence: “{item.quote}”</Text>)}<Text style={styles.assisted}>These guided attempts are shown side by side; no score gain is calculated. Feedback quality remains unreviewed.</Text></View>)}</Card>; }
function Transcript({ linkedTurn, onToggle, open, session }: { linkedTurn?: string; onToggle: () => void; open: boolean; session: SessionDetail }) { return <Card><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={onToggle} style={styles.transcriptToggle}><Text style={styles.dimensionLabel}>Transcript · {session.transcript.length} turns</Text>{open ? <ChevronUp color={colors.cyan} /> : <ChevronDown color={colors.cyan} />}</Pressable>{open ? session.transcript.map((turn) => <View key={turn.id} style={[styles.turn, turn.role === "assistant" && styles.que, turn.id === linkedTurn && styles.que]}><Text style={styles.speaker}>{turn.speaker}{turn.id === linkedTurn ? " · Linked evidence" : ""}</Text><Text style={styles.body}>{turn.text}</Text></View>) : null}</Card>; }
function ListCard({ items, title }: { items: string[]; title: string }) { return <Card title={title}>{items.map((item, index) => <View key={`${title}-${index}`} style={styles.listRow}><Text style={styles.bullet}>•</Text><Text style={styles.body}>{item}</Text></View>)}</Card>; }
const styles = StyleSheet.create({ evidenceLink: { minHeight: 48, justifyContent: "center", paddingVertical: spacing.sm }, back: { alignItems: "center", backgroundColor: colors.panel, borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, minHeight: 48, justifyContent: "center", minWidth: 48 }, assisted: { color: colors.lime, fontSize: 13, fontWeight: "700", lineHeight: 19 }, body: { color: colors.textSoft, flex: 1, fontSize: 14, lineHeight: 21 }, bullet: { color: colors.lime, fontSize: 20 }, comparison: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.xs, paddingTop: spacing.sm }, dimension: { gap: spacing.xs, paddingVertical: spacing.xs }, dimensionLabel: { flexShrink: 1, color: colors.text, fontSize: 15, fontWeight: "800" }, dimensionScore: { color: colors.cyan, fontSize: 14, fontWeight: "900" }, dimensionTop: { flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" }, fill: { backgroundColor: colors.cyan, borderRadius: 99, height: "100%" }, insight: { color: colors.lime, fontSize: 15, fontWeight: "700", lineHeight: 22 }, listRow: { flexDirection: "row", gap: spacing.sm }, muted: { color: colors.muted, fontSize: 13, lineHeight: 19 }, que: { borderLeftColor: colors.cyan }, score: { color: colors.lime, fontSize: 54, fontWeight: "900", letterSpacing: -2 }, scoreRow: { flexWrap: "wrap", alignItems: "center", flexDirection: "row", gap: spacing.md }, scoreUnit: { color: colors.text, fontSize: 18, fontWeight: "800" }, speaker: { color: colors.cyan, fontSize: 11, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" }, track: { backgroundColor: colors.backgroundRaised, borderRadius: 99, height: 8, overflow: "hidden" }, transcriptToggle: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 48 }, turn: { borderLeftColor: colors.borderStrong, borderLeftWidth: 2, gap: spacing.xs, paddingLeft: spacing.md, paddingVertical: spacing.sm } });
