"use client";
import styles from "./mobile-preview-lab.module.css";
export type PreviewQuestionState = { saved: number[]; queue: number[] };
const questions = ["How do you prioritize competing tasks?", "How do you communicate a delay?"];
export function MobileQuestionsPreview({ state, onChange, onLaunch }: { state: PreviewQuestionState; onChange: (state: PreviewQuestionState) => void; onLaunch: (mode: string) => void }) {
  return <div className={styles.mobilePage}><header className={styles.mobileHeader}><p className={styles.mobileEyebrow}>Practice · sample</p><h2>Saved questions</h2><p>Bookmarks remain saved. Practice next tracks your priorities.</p></header><p className={styles.sampleNotice}>Preview only · no learner writes or AI calls</p>
    <section className={styles.mobileCard}><h3>Practice next · general</h3><p>{state.queue.length}/10 questions</p>{state.queue.map((id, index) => <div key={id}><p>{index + 1}. {questions[id]}</p><button type="button" className={styles.textAction} disabled={index === 0} onClick={() => { const queue = [...state.queue]; [queue[index - 1], queue[index]] = [queue[index], queue[index - 1]]; onChange({ ...state, queue }); }}>Move question {index + 1} up</button><button type="button" className={styles.textAction} onClick={() => onChange({ ...state, queue: state.queue.filter(value => value !== id) })}>Remove question {index + 1}</button></div>)}<button type="button" className={styles.mobilePrimary} disabled={!state.queue.length} onClick={() => onLaunch("Rapid Fire")}>Run question set (preview)</button><button type="button" className={styles.textAction} onClick={() => onChange({ ...state, queue: [] })}>Clear Practice next (preview)</button></section>
    {questions.map((question, id) => <section key={id} className={styles.mobileCard}><h3>{question}</h3><button type="button" className={styles.textAction} onClick={() => onChange({ ...state, saved: state.saved.includes(id) ? state.saved.filter(value => value !== id) : [...state.saved, id] })}>{state.saved.includes(id) ? "Bookmarked" : "Save question"} {id + 1}</button><button type="button" className={styles.textAction} disabled={state.queue.includes(id)} onClick={() => onChange({ ...state, queue: [...state.queue, id] })}>Practice next question {id + 1}</button><button type="button" className={styles.mobilePrimary} onClick={() => onLaunch("Coaching")}>Practice with coaching {id + 1}</button></section>)}
  </div>;
}
