"use client";
import styles from "./mobile-preview-lab.module.css";
export type PreviewProgressState = { range?: string; target?: string; another?: boolean; evidence?: boolean };
export function MobileProgressPreview({ state, onChange }: { state: PreviewProgressState; onChange: (value: PreviewProgressState) => void }) {
  return <div className={styles.mobilePage}><header className={styles.mobileHeader}><p className={styles.mobileEyebrow}>Practice evidence · sample</p><h2>Progress</h2><p>See what you practiced and the evidence behind your next step.</p></header><p className={styles.sampleNotice}>Sample only · no learner data, writes, or AI calls</p>
    <section className={styles.mobileCard}><h3>View</h3><div className={styles.progressFilterRow}>{["Active target", "All targets"].map(target => <button type="button" key={target} className={styles.progressFilter} aria-pressed={(state.target ?? "Active target") === target} onClick={() => onChange({ ...state, target })}>{target}</button>)}</div><div className={styles.progressFilterRow}>{["30 days", "90 days", "All time"].map(range => <button type="button" key={range} className={styles.progressFilter} aria-pressed={(state.range ?? "30 days") === range} onClick={() => onChange({ ...state, range })}>{range}</button>)}</div><p>{state.target ?? "Active target"} · {state.range ?? "30 days"}</p></section>
    <section className={styles.mobileCard}><h3>Practice summary</h3><p>3 sessions · 3 initial answers · 1 guided retry</p><p>One question was repeated in a later session. Guided work does not increase independent performance.</p></section>
    <section className={styles.mobileCard}><h3>Teamwork · topic coverage</h3><p>3 practiced answers in 3 sessions. This is not a teamwork score.</p><h4>Recent review finding</h4><p>You explained your personal action.</p><h4>Next improvement</h4><p>Make the result clearer.</p><button type="button" className={styles.textAction} onClick={() => onChange({ ...state, evidence: !state.evidence })}>Open exact supporting answer</button>{state.evidence ? <div><p>Initial answer · saved sample</p><strong>Tell me about working with a colleague.</strong><p>I asked my colleague to explain the issue and documented our agreed next steps.</p></div> : null}</section>
    <section className={styles.mobileCard}><h3>Answer quality · secondary detail</h3><p>Clarity: 3/5 · Coaching · sample model · rubric v1 · independent</p><p>Individual result only. Fewer than three comparable independent sessions: no trend.</p><p>Mixed model, rubric, mode, target or assistance results are not comparable. Older records with unknown provenance remain in History.</p></section>
  </div>;
}
