import type { ProgressAttempt } from "@quesiq/interview-contracts";
import { router } from "expo-router";
import { RefreshControl, Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Screen } from "@/components/ui/screen";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useProgress, useRefetchOnFocus } from "@/lib/useful-progress";
import { useAuth } from "@/providers/auth-provider";
import { colors, spacing } from "@/theme/tokens";
import { useBootstrap } from "@/lib/bootstrap";
import { preferredTargetId } from "@/lib/practice-catalog";

type Target = "active" | "all" | "general";
type Range = "30" | "90" | "all";
export default function ProgressScreen() {
  const { user } = useAuth(); return <ProgressContent key={user?.id ?? "anonymous"} />;
}
function ProgressContent() {
  const { user } = useAuth(); const [target, setTarget] = useState<Target>("active"); const [range, setRange] = useState<Range>("30");
  const bootstrap = useBootstrap();
  const query = useProgress(target, range, bootstrap.data ? preferredTargetId(bootstrap.data) : undefined); useRefetchOnFocus(query.refetch, user?.id);
  if (query.isLoading) return <LoadingState label="Loading progress…" />;
  if (query.isError || !query.data) return <ErrorState message="Progress could not load." onRetry={() => query.refetch()} />;
  const data = query.data; const nextImprovement = (data.attempts ?? []).find((attempt) => attempt.review?.improvement)?.review?.improvement;
  return <Screen bottomInset={false} eyebrow="Evidence, not a score" title="Progress" subtitle="See what you have practiced, where evidence is thin, and which comparisons are reliable." refreshControl={<RefreshControl colors={[colors.cyan]} onRefresh={() => query.refetch()} refreshing={query.isRefetching} tintColor={colors.cyan} />}>
    <View style={styles.row}>{(["active", "all", "general"] as Target[]).map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: target === value }} onPress={() => setTarget(value)} style={[styles.filter, target === value && styles.selected]}><Text style={styles.filterText}>{value === "all" ? "All targets" : value === "active" ? "Active target" : "General"}</Text></Pressable>)}</View>
    <View style={styles.row}>{(["30", "90", "all"] as Range[]).map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: range === value }} onPress={() => setRange(value)} style={[styles.filter, range === value && styles.selected]}><Text style={styles.filterText}>{value === "all" ? "All time" : `${value} days`}</Text></Pressable>)}</View>
    <Card title="Practice counts"><View style={styles.metrics}><Metric value={data.counts.sessions} label="sessions" /><Metric value={data.counts.independentSessions} label="independent sessions" /><Metric value={data.counts.initialAnswers} label="initial answers" /><Metric value={data.counts.subsequentAttempts} label="follow-up attempts" /></View><Text style={styles.note}>{data.counts.repeatedAnswers} repeated answers · {data.counts.unclassifiedSessions} unclassified sessions</Text></Card>
    <Card title="Topic coverage">{data.categories.length ? data.categories.map((category) => <View key={category.key} style={styles.category}><View style={styles.categoryHeader}><Text style={styles.categoryLabel}>{category.label}</Text><Text style={styles.note}>{category.sessions} sessions · {category.answers} answers</Text></View>{category.recent.slice(0, 2).map((attempt) => <Attempt key={attempt.evidence.attemptId} attempt={attempt} />)}</View>) : <Text style={styles.note}>Practice evidence will appear here after you save a session.</Text>}</Card>
    {nextImprovement ? <Card title="Next improvement"><Text style={styles.question}>{nextImprovement}</Text><Text style={styles.note}>From your saved review evidence.</Text></Card> : null}
    <Card title="Quality over time">{data.quality.map((item) => <View key={item.sessionId} style={styles.quality}><Pressable accessibilityRole="button" accessibilityLabel={`Open quality result ${item.date}`} onPress={() => router.push(`/review/${item.sessionId}`)} style={styles.resultLink}><Text style={styles.categoryLabel}>{item.date} · {item.mode}</Text></Pressable><Text style={styles.note}>{item.model} · {item.rubric} · {item.assistance} · {item.targetId ? "Targeted" : "General"}</Text><Text style={item.comparable ? styles.comparable : styles.note}>{item.comparable ? "Comparable result" : `Not comparable: ${item.explanation}`}</Text>{item.scores.map((score) => <Text key={score.key} style={styles.score}>{score.label}: {score.score}/5</Text>)}</View>)}{data.quality.length < 3 ? <Text style={styles.note}>Fewer than 3 individual comparable results are available, so no trend is inferred.</Text> : null}{data.trends.filter((group) => group.results.length >= 3).map((group) => <View key={group.group} style={styles.quality}><Text style={styles.categoryLabel}>{group.label}</Text><Text style={styles.note}>Chronological comparable results:</Text>{group.results.map((result) => <Pressable key={result.sessionId} accessibilityRole="button" accessibilityLabel={`Open trend result ${result.date}`} onPress={() => router.push(`/review/${result.sessionId}`)} style={styles.resultLink}><Text style={styles.note}>{result.date} · {result.scores.map((score) => `${score.label} ${score.score}/5`).join(" · ")}</Text></Pressable>)}</View>)}{data.notes.map((note) => <Text key={note} style={styles.note}>{note}</Text>)}</Card>
  </Screen>;
}
function Metric({ value, label }: { value: number; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.note}>{label}</Text></View>; }
function Attempt({ attempt }: { attempt: ProgressAttempt }) { return <Pressable accessibilityRole="button" accessibilityLabel={`Open evidence for ${attempt.question}`} onPress={() => router.push(`/review/${attempt.evidence.sessionId}?turnIndex=${attempt.evidence.turnIndex}&attemptId=${attempt.evidence.attemptId}`)} style={styles.attempt}><Text style={styles.question}>{attempt.question}</Text><Text style={styles.note}>{attempt.classification === "initial" ? "Initial answer" : attempt.classification === "guided_retry" ? "Guided retry" : "Repeated answer"} · {attempt.date}</Text>{attempt.review ? <><Text style={styles.note}>{attempt.review.finding}</Text><Text style={styles.note}>Next: {attempt.review.improvement}</Text></> : <Text style={styles.note}>No attributable completed review yet.</Text>}</Pressable>; }
const styles = StyleSheet.create({ attempt: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.xs, minHeight: 48, paddingTop: spacing.sm }, category: { gap: spacing.sm }, categoryHeader: { gap: spacing.xs }, categoryLabel: { color: colors.text, fontSize: 15, fontWeight: "800" }, comparable: { color: colors.lime, fontSize: 13, fontWeight: "700" }, filter: { alignItems: "center", borderColor: colors.borderStrong, borderRadius: 999, borderWidth: 1, justifyContent: "center", minHeight: 48, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, filterText: { color: colors.textSoft, fontSize: 13, fontWeight: "700" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, metric: { flex: 1, minWidth: 120 }, metricValue: { color: colors.text, fontSize: 24, fontWeight: "900" }, note: { color: colors.muted, fontSize: 13, lineHeight: 19 }, question: { color: colors.textSoft, fontSize: 14, lineHeight: 20 }, quality: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.xs, paddingTop: spacing.sm }, resultLink: { minHeight: 48, justifyContent: "center" }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, score: { color: colors.textSoft, fontSize: 13 }, selected: { backgroundColor: colors.cyanDark, borderColor: colors.cyan } });
