import "./interview-synthetic";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { getDb } from "@/server/db/client";
import { users, sessions, interviewCoachingInspections, aiRuns, interviewTurnBasedTurns, interviewQuestions } from "@/server/db/schema";
import { executeInspectorAction, readCoachingInspection } from "@/server/interview/coaching-inspector";
import { resolveInterviewExecutionSnapshot, ensureNativeExecutionSnapshot } from "@/server/interview/execution-config";
import { createSession } from "@/server/sessions/create-session";
import { mobileCoachingTurn } from "@/server/interview/chained-coaching-service";
import { saveSessionArtifact } from "@/server/sessions/save-session-artifact";
import { getMobileSessionDetail } from "@/server/sessions/mobile-history";
import { parseSessionSetupSnapshot } from "@/product/session-snapshot";
import { usesMockInterviewPolicy, mockInterviewSpokenContract } from "@/product/mock-interview-policy";
import { buildQueInstructions } from "@/app/api/realtime/session/route";
import { isArtifactTooShortToReview } from "@/product/review-eligibility";

async function main() {
  const url = new URL(process.env.DATABASE_URL!);
  assert(["localhost", "127.0.0.1"].includes(url.hostname) && url.port === "5433");
  const id = `phase5-${randomUUID()}`;
  const originalFetch = globalThis.fetch;
  const oldKey = process.env.OPENAI_INTERVIEW_API_KEY;
  globalThis.fetch = async () => { throw new Error("Unexpected network request"); };
  await getDb().insert(users).values({ id });
  try {
    const context = { preferredName: "Fixture", targetRole: "Engineer", targetCompany: "Example", jobDescription: "Build useful tools." };
    const snapshot = await resolveInterviewExecutionSnapshot({ modeKey: "first_impression", styleKey: "friendly", questionTypeKey: "technical", interviewContext: context }, "native");
    assert.equal(snapshot.controlledModeVersion, 1);
    assert.equal(snapshot.questionTypeKey, undefined);
    assert.equal(snapshot.executionConfig.effective.engine, "turn_based");
    assert.equal(parseSessionSetupSnapshot(snapshot)?.controlledModeVersion, undefined);
    const run = await executeInspectorAction(id, { action: "create", modeKey: "first_impression", context, execution: "simulation", usePersonalContext: false });
    const turn = (turnIndex: number, answer?: string, choice?: "try_again" | "more_feedback" | "move_on") => executeInspectorAction(id, { action: "turn", id: run.id, turnIndex, answer, choice });
    const opening = await turn(0);
    assert.match(String(opening.turns[0].result?.question), /yourself/i);
    await assert.rejects(() => turn(1, " "), /invalid|nonblank/i);
    await turn(1, "I build tools that help teams complete their work.");
    await assert.rejects(() => turn(2, "More feedback", "more_feedback"), /optional retry/);
    const retried = await turn(2, "Try again", "try_again");
    assert.equal(retried.turns[2].result?.question, opening.turns[0].result?.question);
    await turn(3, "I built a reporting tool that reduced weekly manual steps for my team.");
    await assert.rejects(() => turn(4, "Try again", "try_again"), /optional retry/);
    const finished = await turn(4, "Finish", "move_on");
    assert.equal(finished.turns[4].result?.done, true);
    await turn(4, "Finish", "move_on");
    await assert.rejects(() => turn(5, "Late answer"), /Completed/);
    const reopened = await readCoachingInspection(id, run.id);
    assert.equal(reopened.attempts.length, 2);
    assert.deepEqual(reopened.attempts.map((attempt) => attempt.assisted), [false, true]);
    assert.equal((await getDb().select().from(sessions).where(eq(sessions.userId, id))).length, 0);
    await assert.rejects(() => readCoachingInspection("foreign", run.id), /not found/);
    // Same learner service and saved detail, with all provider boundaries mocked.
    process.env.OPENAI_INTERVIEW_API_KEY = "phase5-fixture";
    let modelCalls = 0;
    globalThis.fetch = async (url, init) => {
      if (String(url).endsWith("/v1/audio/speech")) return new Response(new Uint8Array([1, 2]));
      assert.equal(String(url), "https://api.openai.com/v1/responses");
      modelCalls++;
      const request = JSON.parse(String(init?.body));
      assert.match(request.input[0].content, /introduction|tell-me-about-yourself/i);
      const operation = JSON.parse(request.input[1].content).exercise.operation;
      return Response.json({ output_text: JSON.stringify({ state: "opening_question", done: false, question: "Tell me about yourself.", feedback: operation === "question" ? "" : "Connect your experience to the target role.", detectedUserIntent: "awaiting_answer", routingReason: "fixture", targetSkill: "clarity", archetypeId: "" }) });
    };
    const learner = await createSession(snapshot, id);
    const answer = "I build tools that help teams finish their weekly reporting.";
    await mobileCoachingTurn(id, { sessionId: learner.id, turnIndex: 0 });
    await mobileCoachingTurn(id, { sessionId: learner.id, turnIndex: 1, answerTranscript: answer });
    await mobileCoachingTurn(id, { sessionId: learner.id, turnIndex: 2, explicitChoiceIntent: "move_on", answerTranscript: "Finish" });
    assert.equal(modelCalls, 2);
    assert.equal((await ensureNativeExecutionSnapshot(learner.id, id)).controlledModeVersion, 1);
    await saveSessionArtifact(learner.id, id, { endedAt: new Date().toISOString(), durationSeconds: 10, events: [], transcript: [{ id: "answer", createdAt: new Date().toISOString(), role: "user", speaker: "You", text: answer }] });
    const detail = await getMobileSessionDetail(learner.id, id);
    assert.equal(detail?.attempts.length, 1);
    assert.equal(detail?.reviewAccess.kind, "eligible");
    globalThis.fetch = async () => { throw new Error("Unexpected network request"); };
    const legacyRapid = await createSession({ modeKey: "rapid_fire", styleKey: "friendly", interviewContext: context }, id);
    assert.equal((await ensureNativeExecutionSnapshot(legacyRapid.id, id)).executionConfig?.effective.engine, "realtime");
    const rapid = await executeInspectorAction(id, { action: "create", modeKey: "rapid_fire", questionCount: 3, context, execution: "simulation", usePersonalContext: false });
    assert.equal(rapid.snapshot.executionConfig?.effective.engine, "turn_based");
    const rapidTurn = (turnIndex: number, answer?: string) => executeInspectorAction(id, { action: "turn", id: rapid.id, turnIndex, answer });
    let rapidResult = await rapidTurn(0);
    const rapidQuestions: string[] = [String(rapidResult.turns[0].result?.question)];
    await assert.rejects(() => executeInspectorAction(id, { action: "turn", id: rapid.id, turnIndex: 1, choice: "try_again", answer: "Try again" }), /no Coaching choices/);
    await assert.rejects(() => rapidTurn(1, " "), /invalid/);
    for (let i = 1; i <= 3; i++) {
      rapidResult = await rapidTurn(i, `I would first clarify the priorities for scenario ${i}.`);
      const result = rapidResult.turns.at(-1)!.result!;
      assert.equal(result.feedback, undefined);
      assert.equal(result.done, i === 3);
      assert.notEqual(result.state, "brief_feedback_choice");
      if (i < 3) rapidQuestions.push(String(result.question));
    }
    assert.equal(new Set(rapidQuestions).size, 3);
    await rapidTurn(3, "I would first clarify the priorities for scenario 3.");
    await assert.rejects(() => rapidTurn(4, "late"), /Completed/);
    // Actual learner early-end path: an answered queue item must retain its own
    // question even though the returned screen has advanced to the next one.
    const queue = ["How do you prioritize competing tasks?", "How do you communicate a delay?"].map((questionText) => ({ id: randomUUID(), questionText, source: "custom" as const, sourceLabel: "Local fixture", roleFamily: "general", suggestedUse: "practice", targetSkill: "communication", difficulty: "standard" as const }));
    await getDb().insert(interviewQuestions).values(queue.map((question) => ({ ...question, ownerUserId: id })));
    const rapidSnapshot = await resolveInterviewExecutionSnapshot({ modeKey: "rapid_fire", styleKey: "friendly", interviewContext: context, rapidFireQuestionCount: 2, selectedQuestionQueueContext: queue }, "native");
    const rapidLearner = await createSession(rapidSnapshot, id);
    globalThis.fetch = async (url) => {
      assert.equal(String(url), "https://api.openai.com/v1/audio/speech", "Owned question queue must not call a generation model.");
      return new Response(new Uint8Array([1, 2]));
    };
    assert.equal((await mobileCoachingTurn(id, { sessionId: rapidLearner.id, turnIndex: 0 })).question, queue[0].questionText);
    assert.equal((await mobileCoachingTurn(id, { sessionId: rapidLearner.id, turnIndex: 1, answerTranscript: answer })).question, queue[1].questionText);
    const savedRapidTurns = await getDb().select().from(interviewTurnBasedTurns).where(eq(interviewTurnBasedTurns.sessionId, rapidLearner.id));
    assert.equal(savedRapidTurns.find((turn) => turn.turnIndex === 1)?.question, queue[0].questionText);
    await saveSessionArtifact(rapidLearner.id, id, { durationSeconds: 10, endedAt: new Date().toISOString(), endReason: "user_ended", events: [], transcript: [{ id: "rapid-answer", createdAt: new Date().toISOString(), role: "user", speaker: "You", text: answer }] });
    assert.equal((await getMobileSessionDetail(rapidLearner.id, id))?.reviewAccess.kind, "eligible");
    await assert.rejects(() => mobileCoachingTurn(id, { sessionId: rapidLearner.id, turnIndex: 2, answerTranscript: "Late answer" }), /ended/);
    const emptyRapid = await createSession(rapidSnapshot, id);
    await saveSessionArtifact(emptyRapid.id, id, { durationSeconds: 180, endedAt: new Date().toISOString(), events: [], transcript: [] });
    assert.equal((await getMobileSessionDetail(emptyRapid.id, id))?.reviewAccess.canRequest, false);
    globalThis.fetch = async () => { throw new Error("Unexpected network request"); };
    assert.equal((await ensureNativeExecutionSnapshot(legacyRapid.id, id)).executionConfig?.effective.engine, "realtime", "New mode activation cannot change old sessions.");
    const mock = await resolveInterviewExecutionSnapshot({ modeKey: "mock_interview", styleKey: "neutral", turnBasedQuestionCount: 6, interviewContext: context }, "native");
    assert.equal(usesMockInterviewPolicy(mock), true);
    assert.equal(mock.executionConfig.effective.engine, "realtime");
    assert.equal(mock.turnBasedQuestionCount, undefined);
    const prompt = mock.executionPromptSnapshot.configs.find((p) => p.key === "realtime_interviewer")!;
    assert.equal(mock.executionConfig.effective.realtimeModel, prompt.model, "Do not replace the pinned configured Realtime model.");
    const instructions = buildQueInstructions(prompt, mock, mock.executionPromptSnapshot.components);
    assert(instructions.includes(mockInterviewSpokenContract));
    assert.doesNotMatch(instructions, /In Coaching mode, give one concrete coaching point/);
    const legacyMock = await createSession({ modeKey: "mock_interview", styleKey: "neutral", interviewContext: context }, id);
    const legacyMockSnapshot = await ensureNativeExecutionSnapshot(legacyMock.id, id);
    assert.equal(usesMockInterviewPolicy(legacyMockSnapshot), false, "Do not silently reprompt a pre-existing session.");
    assert.notEqual(legacyMockSnapshot.executionConfig?.revision, mock.executionConfig.revision);
    assert.equal(usesMockInterviewPolicy(parseSessionSetupSnapshot(mock)), false, "Public snapshot parsing must discard policy pins.");
    const mockArtifact = { endedAt: new Date().toISOString(), durationSeconds: 120, events: [], transcript: [{ id: "mock-answer", createdAt: new Date().toISOString(), role: "user" as const, speaker: "You" as const, text: answer }] };
    assert.equal(isArtifactTooShortToReview(mock, { ...mockArtifact, durationSeconds: 119 }), true);
    assert.equal(isArtifactTooShortToReview(mock, { ...mockArtifact, durationSeconds: undefined }), true);
    assert.equal(isArtifactTooShortToReview(mock, { ...mockArtifact, transcript: [] }), true);
    assert.equal(isArtifactTooShortToReview(mock, mockArtifact), false);
    const mockLearner = await createSession(mock, id);
    await saveSessionArtifact(mockLearner.id, id, mockArtifact);
    assert.equal((await getMobileSessionDetail(mockLearner.id, id))?.reviewAccess.kind, "eligible");
    assert.equal(await getMobileSessionDetail(mockLearner.id, "foreign"), undefined);
    await assert.rejects(() => ensureNativeExecutionSnapshot(mockLearner.id, id), /ended/);
    console.log("Phase5 First Impression: controller, retry bounds, replay, isolation, mocked learner path and saved review passed.");
    console.log("Phase5 Rapid Fire: fixed count, no feedback/choices, empty/replayed/late input and legacy engine preservation passed.");
    console.log("Phase5 Mock Interview: versioned no-coaching policy, pinned Realtime model, legacy compatibility, duration/content gates and saved owned review passed.");
  } finally {
    globalThis.fetch = originalFetch;
    if (oldKey === undefined) delete process.env.OPENAI_INTERVIEW_API_KEY; else process.env.OPENAI_INTERVIEW_API_KEY = oldKey;
    await getDb().delete(aiRuns).where(eq(aiRuns.userId, id));
    await getDb().delete(interviewCoachingInspections).where(eq(interviewCoachingInspections.userId, id));
    await getDb().delete(sessions).where(eq(sessions.userId, id));
    await getDb().delete(users).where(eq(users.id, id));
  }
}
main().then(() => process.exit(0)).catch((error) => { console.error(error); process.exit(1); });
